YouPlay2019/YouPlay2019/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using YouPlay2019.DAO;
using YouPlay2019.Models;

namespace YouPlay2019.Controllers
{
    public class AlunoController : PadraoController<AlunoViewModel>
    {
        public AlunoController()
        {
            DAO = new AlunoDAO();
        }

        public override IActionResult Index()
        {
            ViewBag.Operacao = "I";
            ViewBag.Erro = null;

            AlunoViewModel aluno = new AlunoViewModel();

            try
            {
                ListagemViewBag();
                return View(aluno);
            }
            catch (Exception erro)
            {
                ViewBag.Erro = erro.Message;

                ListagemViewBag();
                return View(aluno);
            }
        }

        protected override void ListagemViewBag()
        {
            base.ListagemViewBag();

            List<BagSelectViewModel> listagemStatusAluno = DAO.ListagemSelect("aluno_status");
            List<BagSelectViewModel> listaEscolaridade = DAO.ListagemSelect("escolaridade");
            List<BagSelectViewModel> listaAlunoResponsavel = DAO.ListagemSelect("vinculo");

            ViewBag.StatusAluno = listagemStatusAluno;
            ViewBag.EscolaridadeAluno = listaEscolaridade;
            ViewBag.VinculoAlunoResponsavel = listaAlunoResponsavel;
        }

        protected override void ValidaDados(AlunoViewModel model, string operacao)
        {
            base.ValidaDados(model, operacao);

            if (model.Imagem == null)
            {
                ModelState.AddModelError("Imagem", "Escolha uma imagem.");
            }
            else if (model.Imagem.Length / 1024 / 1024 >= 2)
            {
                ModelState.AddModelError("Imagem", "Imagem limitada a 2 mb.");
            }

            if (model.Nome == null)
            {
                ModelState.AddModelError("Nome", "Nome não informado");
            }

            if (string.IsNullOrEmpty(model.DataNascimento.ToString().Trim()))
            {
                ModelState.AddModelError("DataNascimento", "Data de nascimento não informado");
            }

            if (model.Rg.Trim() == null)
            {
                ModelState.AddModelError("Rg", "Número de RG inválido");
            }
            else if (model.Rg.Length != 9)
            {
                ModelState.AddModelError("Rg", "Número de RG inválido");
            }

            if (model.Cpf.Trim() == null)
            {
                ModelState.AddModelError("Cpf", "Número de CPF inválido");
            }
            else if (model.Cpf.Length != 11)
            {
                ModelState.AddModelError("Cpf", "Número de CPF inválido");
            }

            if (model.Telefone.Trim() == null)
            {
                ModelState.AddModelError("Telefone", "Número de telefone inválido");
            }
            else if (model.Telefone.Length > 13)
            {
                ModelState.AddModelError("Telefone", "Número de telefone inválido");
            }

            if (model.Email.Trim() == null)
            {
                ModelState.AddModelError("Email", "Email inválido");
            }

            if (model.Cep == null)
            {
                ModelState.AddModelError("Cep", "Cep informado inválido");
            }
            else if (Convert.ToInt32(model.Cep) <= 0 || model.Cep.ToString().Length != 8)
            {
                ModelState.AddModelError("Cep", "Cep informado inválido");
            }

            if (model.Numero.ToString().Trim() == null)
            {
                ModelState.AddModelError("Numero", "Número inváido");
            }
            else if (model.Numero < 0)
            {
                ModelState.AddModelError("Numero", "Número inváido");
            }

            if (model.NomeResponsavel == null)
            {
                ModelState.Remove("NomeResponsavel");
            }

            if (model.RgResponsavel == null)
            {
                ModelState.Remove("RgResponsavel");
            }
            else if (model.RgResponsavel.Length != 9)
            {
                ModelState.AddModelError("RgResponsavel", "Rg inválido");
            }

            if (model.CpfResponsavel == null)
            {
                ModelState.Remove("CpfResponsavel");
            }
            else if (model.CpfResponsavel.Length != 11)
            {
                ModelState.AddModelError("CpfResponsavel", "CPF inválido");
            }

            if (model.TelefoneResponsavel == null)
            {
                ModelState.Remove("TelefoneResponsavel");
            }
            else if (model.TelefoneResponsavel.Length > 13)
            {
                ModelState.AddModelError("TelefoneResponsavel", "Telefone inválido");
            }
        }
    }
}

YouPlay2019/YouPlay2019/Controllers/DisciplinaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using YouPlay2019.DAO;
using YouPlay2019.Models;

namespace YouPlay2019.Controllers
{
    public class DisciplinaController : PadraoController<DisciplinaViewModel>
    {
        public DisciplinaController()
        {
            DAO = new DisciplinaDAO();
        }

        public override IActionResult Index()
        {
            ViewBag.Operacao = "I";
            ViewBag.Erro = null;

            DisciplinaViewModel disciplina = new DisciplinaViewModel();

            return View("Index", disciplina);
        }
    }
}

YouPlay2019/YouPlay2019/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using YouPlay2019.Models;
using YouPlay2019.DAO;

namespace YouPlay2019.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login(UsuarioViewModel model)
        {
            try
            {
                LoginDAO dao = new LoginDAO();
                UsuarioViewModel usuarioLogado = dao.ObtemUsuario(model);

                if (usuarioLogado != null)
                {
                    HttpContext.Session.SetString("Logado", "true");
                    ViewBag.Logado = HelperController.VerificaUserLogado(HttpContext.Session);
                    return RedirectToAction("Index", "Professor");
                }
                else
                {
                    ViewBag.Erro = "Usuário ou senha inválidos!";
                    return View("Index");
                }
            }
            catch (Exception ex)
            {
                ViewBag.Erro = ex.Message;
                return View("Index");
            }
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

YouPlay2019/YouPlay2019/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>Escola de música YouplaY</title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
    <link rel="icon" href="~/Imagens/favicon.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/Imagens/apple-icon.png" />

    <script type="text/javascript" src="~/js/cep.js"></script>
</head>
<body class="layout-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light navbar-transparente mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Imagens/Saxlogo.png" height="60" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon" style="color: black"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 nav-pills justify-content-end">
                        <li class="nav-item dropdown mr-3">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Alunos
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                                <a class="dropdown-item" asp-controller="Aluno" asp-action="Index">Cadastrar Aluno</a>
                                <a class="dropdown-item" asp-controller="Aluno" asp-action="Consulta">Consultar Aluno</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown mr-3">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Professores
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                <a class="dropdown-item" asp-controller="Professor" asp-action="Index">Cadastrar Professor</a>
                                <a class="dropdown-item" asp-controller="Professor" asp-action="Consulta">Consultar Professor</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown mr-3">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Disciplinas
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                                <a class="dropdown-item" asp-controller="Disciplina" asp-action="Index">Cadastrar Disciplina</a>
                                <a class="dropdown-item" asp-controller="Disciplina" asp-action="Consulta">Consultar Disciplina</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active btn" asp-area="" asp-controller="Login" asp-action="Logout">
                                <i class="far fa-user"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container p-2">
        <div class="card">
            <div class="card-body">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container text-white">
            <div class="row">
                <div class="col-md-8">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link">
                                &copy; 2019 - YouPlay2019 - Code by Marcelo & Thiago
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="nav justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#"><i class="fab fa-lg fa-facebook-square"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#"><i class="fab fa-lg fab fa-twitter-square"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#"><i class="fab fa-lg fa-instagram"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#"><i class="fab fa-lg fa-github-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>